jcms_ammo_crate=无限弹药箱
jcms_apc=装甲运兵车
jcms_beam=伤害射线
jcms_breakable=可破坏物
jcms_bullseye=靶心
jcms_charpleball=焦尸肉球
jcms_deathraycontroller=轨道激光控制
jcms_deathray=轨道激光
jcms_downloadpillar=数据柱
jcms_dropflare=照明弹
jcms_droppod=空投舱
jcms_dynamicsupply=区域肃清者动态物品
jcms_emplacement=激光炮座
jcms_energyfield=能量护盾
jcms_evac=撤离点
jcms_fire=火区
jcms_flashpoint=冲突点
jcms_jammer=RGG 干扰器
jcms_jumppad=跳跃垫
jcms_landmine=爆炸物
jcms_mainframe=RGG 主计算机
jcms_micromissile=微型导弹
jcms_node=节点
jcms_npcportal=NPC 黑洞
jcms_orechunk=矿石块
jcms_orecrate=矿石板条箱
jcms_orevein=矿脉
jcms_payload=运载目标
jcms_radsphere=辐射球
jcms_refinery=精炼厂
jcms_respawnbeacon=重生信标
jcms_restock=补给板条箱
jcms_sapper=J公司装置
jcms_shieldcharger=护盾充能器
jcms_shop=商店
jcms_smokenade=烟雾弹
jcms_sniperround=狙击枪弹药
jcms_stormmanager=风暴管理器
jcms_tank=LHT-6 坦克
jcms_terminal=终端
jcms_tesla=特斯拉电圈
jcms_turret=炮塔
jcms_turret_smrls=导弹平台
jcms_vanguard_backpack=先锋背包
jcms_vtol=DS-2 垂直起降运输机
jcms_zombiebeacon=核弹
jcms_zombieumbrella=雨伞
npc_jcms_boomer=爆裂者
npc_jcms_dog=阿狗
npc_jcms_reaper=蚁狮收割者
npc_jcms_spirit=幽灵
npc_jcms_zombiepolyp=息肉
npc_jcms_zombiespawner=巢穴