jcms.bestiaryselectnpc=选择 NPC
jcms.bestiaryhealth=生命值
jcms.bestiarybounty=赏金

jcms.bestiary_antlion_cyberguard=赛博守卫
jcms.bestiary_antlion_cyberguard_desc=这是由黑手党研发部门专门设计来惹怒我们的一种升级版蚁狮守卫。它们内部主要还是有机的。然而，它们的外壳大部分已被看起来令人生畏的电子元件和金属所取代。它们还有能力对附近的友军施加一次性的球形护盾，该护盾能精准吸收任何伤害一次，无论该伤害是弱还是强。不管怎样，这些野兽（不知为何）比自然诞生的守卫要弱，但它们覆盖装甲的皮肤进一步降低了来自低伤害武器的危害。最好用重型、慢射速的武器和爆炸物穿透它们的护甲。尽管如此，从统计学上看，你们这群白痴肃清者总是死盯着你们在多元宇宙中找到的任何花哨的、高射速的、高DPS的狗屎枪支。所以，是的，直接向赛博守卫开枪射击应该也足以放倒它了。

jcms.bestiary_antlion_drone=工蚁
jcms.bestiary_antlion_drone_desc=一种常见的蚁狮。这个特定变种是一个没有头脑的工蚁，甚至不会做基础数学，也干不了办公室的活（尽管如果我们把它们中的一个撤离到母舰上，我们很轻松就能给它打上领带并塞进一个办公隔间）。有些蚁狮会说话，有些甚至表现得完全像人类——那些蚁狮通常会四处闲逛，凝视着虚空……但十有八九，它们会被正在读这段话的你给谋杀。不管怎样，如果它们碰巧是变形的人类——你知道的，就是那些报名参加“让我们做些疯狂的科学狗屎并重演卡夫卡《变形记》”周报的白痴之一——你不应该为杀了它们而感到内疚。事实上，你是在帮它们的忙，因为这是它们在人类身体中回到家乡重生的最快方式。希望如此吧。好了，我跑题了。好吧，那么蚁狮呢？它们会飞并且会成群结队地扑向你。射爆它们就行！高射速武器是首选。

jcms.bestiary_antlion_guard=蚁狮守卫
jcms.bestiary_antlion_guard_desc=我们不确定它们是否与普通的蚁狮工蚁属于同一物种……但我们确切知道的是，这些蛮子绝对残忍无情且势不可挡。它们只需推一下就能轻松摧毁我们的炮塔，让它们着着火飞出去。所以对于那些喜欢自动杀戮的粉丝来说，这可是个坏消息。除此之外，它们实际上比看起来要弱一些。试着在它们身上绑一个定时炸药，它会在 10 秒后灰飞烟灭。不过请确保你能跑得过它。否则，炸弹会带你一起上路。

jcms.bestiary_antlion_burrowerguard=掘地守卫
jcms.bestiary_antlion_burrowerguard_desc=一种特殊类型的蚁狮守卫，根据我们的了解，它们更喜欢将大部分生命花在地下。它们看护幼虫，并做昆虫认为重要的任何事情。“那它们为什么出来打我们？”好问题！虽然我们不知道为什么可能有人讨厌 J公司，但我们确实认为肃清者在任务期间引起的喧闹声非常令人讨厌，以至于连本来没有感情的昆虫都感到恼火。所以，掘地守卫就出来了。它们不怎么喜欢待在外面，而且明显比其他蚁狮弱得多……然而，它们可以并且将会钻回地下，然后在任何地方钻出来——甚至在室内——摧毁所有噪音来源！

jcms.bestiary_antlion_reaper=收割者
jcms.bestiary_antlion_reaper_desc=这些家伙在本质上是机械的、有机的还是魔法的，至今仍是个谜。当我们第一次看到它们时，黑手党对我们发送的“那他妈的是什么鬼东西”的电子邮件根本不予回复。因此，我们能提供的信息有限。听起来虽然很狂野，但“收割者”是重型的、不会飞的蚁狮，它们拥有漂浮的球状眼睛，可以发射横扫的激光束……有些人觉得它们很吓人，有些人觉得它们很搞笑。躲开那些光束，你就会没事的。我们不认为它们具备近战能力。

jcms.bestiary_antlion_ultracyberguard=ACLP-1
jcms.bestiary_antlion_ultracyberguard_desc=在设计了赛博守卫之后，黑手党更进了一步，制造了一个完全机器人版本的守卫。虽然说实话，我们还是不知道他们怎么称呼它们。J公司的首席执行官 JonahSoldier 瞥了它一眼，用索然无味的语气说了句“终极赛博守卫”，然后就回去忙他的工作了。我们觉得叫它“终极赛博守卫”不足以让肃清者产生足够的恐惧，所以我们给它起了一个很酷的首字母缩写。它代表“蚁狮赛博激光平台 (Antlion Cybernetic Laser Platform)”。与普通的守卫相比，它更敏捷，也更具攻击性，尽管它很容易被杀死。它的头部有一门激光炮（老实说，这似乎只是雷声大雨点小），它的缩写就是从这里来的。尽管是定制设计和大规模生产，黑手党似乎根本没有将 ACLP 作为常规战斗单位使用，这可能是因为它们的效率低下。也就是说，他们设计这个东西只是为了恶心我们，没有别的目的。又一次。当真的吗？

jcms.bestiary_antlion_waster=废土工蚁
jcms.bestiary_antlion_waster_desc=基本上，这就是一种更小、更弱的蚁狮工蚁。不，它们根本不是“幼年蚁狮”。事实上，这似乎是某种瘦弱的成年体，由于其天生体型小而无法繁殖。这也让它们变得异常凶猛。它们很容易被杀死，但它们会尽一切努力来抓你。废土工蚁心中充满了仇恨，以至于它们可能也会攻击更大的蚁狮……但这似乎并没有发生。它们会感到恐惧吗？

jcms.bestiary_antlion_worker=蚁狮工兵
jcms.bestiary_antlion_worker_desc=进化赋予了这些虫子喷吐酸液的能力。通常情况下，当它们不想杀你的时候，它们会用酸液来挖掘隧道。而且，不用说，它融化我们坦克和炮塔的金属装甲就像溶解岩石一样容易。工兵会尽量待在后方来瘫痪你们的防御设施。此外，杀死它们会使它们爆裂，并在附近的任何东西上覆盖酸液，所以要小心。

jcms.bestiary_combine_cybergunship=扫射炮艇
jcms.bestiary_combine_cybergunship_desc=为使用腹部光束炮进行了超强优化的炮艇。它们身上洋溢着致命的蓝色能量。所以别闲逛了，士兵；你应该知道蓝色对商业和 J公司整体来说有多糟糕。它们的火炮已经升级，可以发射爆炸性弹药，而且它们会比普通炮艇更频繁地使用激光。当你听到警报声时，继续跑！扫射炮艇不仅只进行一次扫射，它们会一直追着你，所以仅躲避一次是没用的。

jcms.bestiary_combine_elite=精英士兵
jcms.bestiary_combine_elite_desc=一位高级的守卫军士兵，在我们入侵并在“15分钟的混战”后完全控制了宇宙联邦的所有主世界及其附属宇宙之后，由 J公司 进一步增强。我们给这些家伙配备了磁力护盾，与肃清者防护服中内置的护盾没什么两样。我们偏爱这些士兵的原因是因为他们有一只很酷的红眼，而我们喜欢所有红色的东西。不管怎样，关键是，J公司从你与联合军的交战中赚取利润。我们命令联合军与你战斗，我们付钱让你与联合军战斗，这是我们最伟大、最赚钱的商业策略之一。精英士兵携带 AR2 脉冲步枪，可以发射暗能量球，这些能量球会以意想不到的方式重新放置你的炮塔。我们也听到过关于手持冲锋枪的精英士兵在逃的谣言，但请放心，这可能只是谣言。大概吧。

jcms.bestiary_combine_gunship=炮艇
jcms.bestiary_combine_gunship_desc=飞行的战斗合成体，看起来就像被改造过的太空海豚。它们极具攻击性，对炮塔毫不留情（它们认为炮塔是对它们自身形象的拙劣嘲弄）。这就是为什么——你猜对了——炮艇会迅速让你失去防御能力，即使它们嘴部的机枪本身并不会直接造成危险。如果你够幸运，在地图上有可进入的建筑物或地下区域肃清，你可以轻松躲在室内避开炮艇。否则，使用轨道激光和防空导弹在它们充能发射毁灭性的腹部光束炮之前将其击落。对了对了对了，它们的腹部光束炮……炮艇能够直接在它们下方发射出强大的蓝色光束。站在光束中超过一秒必定死亡。所以当你看到周围变得比平时更蓝时，你最好往旁边走几步。

jcms.bestiary_combine_hunter=猎人
jcms.bestiary_combine_hunter_desc=也被称为“迷你三脚机甲”，猎人是残暴的小混蛋，旨在吸引你的注意力。它们内置了一门爆炸性的飞镖炮，可以向你冲锋并用身体猛击将你击退。然而，尽管它们外表雄伟、天性凶恶，它们却很容易被杀死。猎人特别害怕爆炸物和钝器敲击它们的头部，这意味着手持重力枪的工程师可以在不发射一颗子弹的情况下杀死猎人：只需把炮塔扔向它！（尽管，无可否认，直接把猎人射死更快）。

jcms.bestiary_combine_metrocop=国民警卫队
jcms.bestiary_combine_metrocop_desc=被从城市巡逻任务中抽调出来的警察，只是为了试着踢你的屁股。国民警卫队带着一台飞锯。飞锯本身并没有什么危险的，但它们却很烦人：浪费一颗子弹，还会重置你的护盾恢复。你看到的大多数国民警卫队都不太习惯真正的战斗。他们通常的工作是在出价最高的派系（通常是 J公司）控制的领土上巡逻，站在爆炸桶旁边，时不时地说一两句具有环境叙事性的一句话台词。这可是份梦想中的工作，对吧？所以你可以想象，当他们突然被拉进传送门，并被告知：“好吧，在你倒下之前，给这个穿着红色衣服、到处连跳的混蛋造成点伤害”时，他们会有多沮丧。国民警卫队也挺失眠的，所以他们只是大致朝着你的方向开枪，并希望飞锯能完成剩下的工作。你杀了他们之后，他们会在他们以前待的地方重生，叹口气，摘下面具，抽根烟，然后继续轮班。

jcms.bestiary_combine_scanner=扫描仪
jcms.bestiary_combine_scanner_desc=将信息传回给它们所属小队的飞行小无人机。一旦你被一只扫描仪发现，你可以确定一支守卫军小队正在朝你赶来。它们在其他方面是无害的，尽管它们确实会分散炮塔的注意力，并且在被击落时会向你进行神风特攻。扫描仪顶多也就是很烦人。幸运的是，至少它们似乎不会用强光闪瞎你的眼睛。

jcms.bestiary_combine_sniper=狙击手
jcms.bestiary_combine_sniper_desc=拥有完美精度的等离子狙击步枪、射程极远且烦人的刺头。不过，子弹的速度刚好慢到你可以躲开。只要你听到枪声，就赶紧离开。当他们的联合军主世界老师（或者是别的什么人）问他们长大后想成为什么样的人时，他们回答说：“呃，你懂的，一个彻底的傻逼。”狙击手将是你会眼睁睁看着炮塔一个接一个消失的原因。他们会是你无法安静站着骇入终端片刻的原因。他们所做的事情毫无荣誉可言。

jcms.bestiary_combine_soldier=士兵
jcms.bestiary_combine_soldier_desc=联合军已将许多志愿者转化为赛博士兵，什么什么“守卫军超人类部队”之类的。据说，这些是终极战士：顺从、无畏，诸如此类。事实是，他们就是炮灰，但数量众多时极其致命。他们能够使用各种战术（主要是包抄）向你造成确实的伤害。联合军士兵装备有冲锋枪、AR2和霰弹枪，并携带着可以被扔回去的手榴弹。拿冲锋枪的会试图包抄你，拿 AR2 的大部分会原地射击，而拿霰弹枪的会向你冲锋。

jcms.bestiary_combine_suppressor=镇压者
jcms.bestiary_combine_suppressor_desc=手持强力机枪的联合军重装兵。镇压者的主要作用正如其名，他们很肉且很危险，但速度很慢。你几乎永远不会看到他们一边跑一边开枪，这也是为什么他们很容易被集火消灭的原因。然而，如果置之不理，其中一名士兵会亲自用一阵弹雨把你拖入地狱。或者是你的炮塔。我有没有提过他们撕碎你炮塔的速度有多快？好吧，你以后会明白的。

jcms.bestiary_rebel_alyx=爱丽克斯·凡斯
jcms.bestiary_rebel_alyx_desc=这个难以捉摸的女人看起来可能像个干练的黑客，只要盯着我们的机器就能控制它们，但现实却严峻得多。作为一名高级赌徒，她已经赌了太多次了，以至于她的血管里流淌的简直是赌博素而不是血液。她只需触摸一下，就足以给我们的炮塔注入足够的紫色，把它们也变成赌徒。幸运的是，你的电击棍注入了 J，它可以治愈赌博，所以你所需要做的就是用它敲击一下，被“骇入”的物体就会想起 J公司 强制要求的关于市场份额、西装和红色的课程。她过去也曾把我们的肃清者变成赌徒，但看来她最近赌得不够多，所以没有成功。

jcms.bestiary_rebel_dog=阿狗
jcms.bestiary_rebel_dog_desc=这东西诞生于对机械物体的纯粹仇恨之中。不管是房屋水管、复杂的通信阵列，还是你的步哨巢穴——这东西只要看到它们，就会感到仇恨。然后它会跑过去，抓住它，哪怕这玩意被他妈的用螺栓固定在地板或墙上，然后把它扔向最近的非紫色的东西（这会造成极大的伤害！），或者把它们带给爱丽克斯让她骇入，因为尽管它讨厌所有工程学的东西，但它也喜欢传播赌博。它也重到足以施展地面砸击，并将所有东西击飞到空中，所以要小心。它似乎否认自己也是机械的性质。Traeesen 已要求我们不要提醒它这一点，因为它正在为此接受治疗。

jcms.bestiary_rebel_fighter=战士
jcms.bestiary_rebel_fighter_desc=普通的赌徒。他们的装备比我们部队的便宜得多，也破旧得多，因为他们赚的任何利润都被赌光了。然后他们还敢抱怨自己的“生活质量太差”。这对你来说本该是个优势，但尽管他们很穷，他们却惊人地难以杀死。也许正是他们的纯粹愚蠢让他们活了下来。我们曾多次试图教他们商业、投资和股票知识，但根本行不通。他们就像抗子弹一样把这些知识抗了下来。帮我个忙，对这些环保主义者不要有丝毫的仁慈。

jcms.bestiary_rebel_helicopter=RGG 直升机
jcms.bestiary_rebel_helicopter_desc=RGG 试图嘲弄我们，给我们写信吹嘘他们的“天才工程师”是如何创造出“辉煌的空中杀戮机器”的。让我告诉你一个秘密。我们的科学业务部门检查了其中一架，你猜怎么着！它们实际上就是用胶水粘在一起凑成一架直升机形状的老虎机。除此之外，它们只是连接了几把枪，并且有一个放置货物的狭小空间，可以从那里投放（我们的！）被骇入的炮塔。飞行员甚至没有头盔，只有一根用来赌博的杠杆。我们不确定它究竟是如何飞行的，更不用说找到前往敌人的路并向他们射击了。我们的主导理论是，飞行员实际上在赌要飞向哪个方向以及向哪个方向射击，并且很幸运地让这架直升机看起来像是真的在跟踪并瞄准你。不管怎样，与我们先进的炮艇不同，这些东西是用从超市买来的紫色胶水粘在一起的。尽情向它们射击吧——它们很快就会掉下来的。

jcms.bestiary_rebel_medic=医疗兵
jcms.bestiary_rebel_medic_desc=RGG 没有一个人有医疗保险，即便他们有，通常也赌光了。他们对这个原本会使人虚弱的社会经济灾难的解决方案是：取点水，把它染成绿色，装进一个用过的医疗包里（通常是从我们这里偷来的），然后把它倒在伤员身上。这些家伙随身携带那些东西，把“医疗包”敷在伤员身上。它该死地好用，我们的科学家也在研究这个。你应该记住的一点是，赌徒不是很聪明，所以他们可能会认为你和他们是一伙的。如果你设法做到视距内不射击他们（我知道他们是紫色的，但就请忍耐一下），你甚至可能设法让其中一个人来治疗你。

jcms.bestiary_rebel_megacopter=执法者直升机
jcms.bestiary_rebel_megacopter_desc=很多时候，每当 J公司 需要某个东西表现更好时，我们会把它涂得更红，或者给它打上商业领带穿上西装，或者把它的名字改成有更多的 J，或者给它属于自己的小办公隔间。RGG 注意到了我们的策略，并通过我们只能假设是 Traeesen 一生中最糟糕的淋浴冥想，他开始让他的直升机也去赌博，这使它们变得更加强大。显然，他们的赌场有专供直升机使用的老虎机。直升机似乎非常容易沉迷赌博（也许是因为它们本身就是老虎机？），并且它们非常轻松地爬上了赌博排行榜。如果你认为这个东西上面的 RGG 标志只是新涂的一层漆，那你就错了——它们是纹身，所有 RGG 执法者似乎都以此自豪，也许作为忠诚的标志。在任何情况下，这些东西内部都蕴含着如此多的原始赌博能量，以至于它们都变成了紫色，而这似乎在某种程度上保护了它们。但这并没有什么是老一套的“射爆那个东西直到它爆炸”解决不了的。

jcms.bestiary_rebel_odessa=奥德萨·卡伯居
jcms.bestiary_rebel_odessa_desc=一位来自过去时代的著名上校，奥德萨·卡伯居在第一次起义期间勇敢地领导反抗军部队对抗联合军（那是在联合军被 J公司 同化之前……因此反抗军赢得了那场战争。咳咳。Jod，可惜我们公司当时不存在。不然我们会把双方都踢回办公隔间并向所有人收税）。猎人、炮艇、三脚机甲……你能想到的。他他妈的徒手把它们的大脑扯出来，当场吃掉！他是个相当硬汉的角色。当他的拳头弹药耗尽或无法使用时，他就会使用他的 RPG。显然，他就是那么厉害，所以他们后来提取了他的 DNA。因此他被快速克隆了——包括他脏兮兮的衣服、RPG 和所有东西——来建立一支军队。不幸的是，他的大脑有点退化了，所以他的克隆人不再那么强硬了。又或者，他一直在讲的故事全都是狗屎（在过去更简单的日子里人们相信了他的话）。不管怎样，他有一把 RPG，并且被指示用它来对付我们。如果你的准心够好，你应该能够在他发射的火箭弹到达你之前将其击落。

jcms.bestiary_rebel_rgg=RGG 步兵
jcms.bestiary_rebel_rgg_desc=如果你认为普通的 RGG 叛军是无脑的——那就等你听完这个吧。这些家伙几乎甚至不存在！他们之所以尖叫得那么厉害，是因为一旦战场的肾上腺素击中他们偶尔存在的偶尔脑子，这会让他们产生足够的意识来形成他们的第一个想法。你关心的是子弹对他们往往不起作用，这给最早的肃清者小队带来了麻烦。幸运的是，在与 RGG 头目 Traeesen 进行了激烈的外部交涉后，他让他们的行为变得确定了——现在，对他们的前几次攻击将直接穿透，但下一次攻击将立即杀死他们。换句话说，他们没有“生命值 (HP)”，他们可以承受的命中次数是有限的，无论攻击有多强。我知道你们可能很难忍住不把 3 发火箭弹倾泻到任何你看到的东西上，但我们建议对付这些家伙时使用便宜的弹药。这对生意有好处。

jcms.bestiary_rebel_vanguard=先锋
jcms.bestiary_rebel_vanguard_desc=等等，你是说这家伙是我帮——我是说 RGG 的一部分？真的吗？他有登记在册之类的吗？我不知道这家伙到底是谁。我的意思是，我当然不需要知道……我是 J公司 的一员……呃，他到底是干什么的？好吧，他有一把霰弹枪，而且他的弹药是……着火的？这火甚至也是紫色的吗？好吧，我稍后会找他谈谈并解决这个问题。好吧，他会在射击的地方留下火焰，所以要小心。我想，除此之外他应该不会造成太大麻烦。

jcms.bestiary_rebel_vortigaunt=弗地冈人
jcms.bestiary_rebel_vortigaunt_desc=我从来没有真正理解过为什么 RGG 有时候……就是绿色的？我的意思是，我很确定他们和我们有着一样的本能，想要杀死所有不是他们主色的东西。这就像他们认为绿色就是紫色一样。无论如何，在它们攻击你之前干掉它们。它们发射的射线造成巨大伤害，并且会让你产生幻觉。我有一次被击中，我看到了那些至今仍让我彻夜难眠的奇怪幻觉。关于天使的幻觉，回合制的战术游戏，天空中一朵奇怪的花，我确切的 IP 地址和家庭住址——好吧，也许最后一部分与这无关。你还应该知道，这些完美的人类公民将通过向他们的赌徒同伴授予绿色护盾来援助他们，而且因为你们这些乌合之众肃清者大概都有点赌博的黑历史，如果时机把握得当，你可以利用这一点来完全恢复你的护盾，并立即重返战场。

jcms.bestiary_zombie_boomer=爆炸者
jcms.bestiary_zombie_boomer_desc=爆炸者是被爆裂蟹感染的僵尸。它们近 80% 的体重是由腐烂的血液和幼年爆裂蟹组成的。它们体内几乎没有剩下任何肌肉能向你抬起手，但在被靠近时，它们会因为过度刺激而爆裂，这将释放出大约 7 只爆裂蟹到空地上。一定要射击爆炸者，即使在它们开始爆裂之后——这会杀死里面的爆裂蟹，让你需要对付的爆裂蟹变少。通过特别是使用致命手段杀死爆炸者，例如使用爆炸物或超高温等离子体，将确保不会留下任何蟹让你担心。你也可以尝试对它们使用电击棍——那会把爆炸者击退，并为内部的爆裂蟹准备一次强烈的爆炸！好好利用它来获取优势。

jcms.bestiary_zombie_charple=焦尸
jcms.bestiary_zombie_charple_desc=烧焦的、被附身的尸体——焦尸是僵尸生成器以埋在地下的尸体为食并将其残骸吐到地表的副产品。虽然它们很弱，可以被一枪毙命，但焦尸冷酷无情，会造成大量伤害。它们中的一个能够用一次飞跃几乎完全摧毁一个新放置的炮塔。一定要尽快处理它们，但更好的办法是，处理掉它们的来源！

jcms.bestiary_zombie_combine=联合军僵尸
jcms.bestiary_zombie_combine_desc=爆炸跑者、活体炸弹、行走的起爆器。随你怎么称呼它们。这些有自杀倾向的混蛋肯定会抛弃他们的朋友、生命、工作和积蓄，只为了确保带你一起被炸碎。如果你看到其中一个从口袋里掏出手榴弹，你也做同样的事。只是别抛弃你的工作。此外，值得一提的是，如果你真的偶然发现了一个能够控制内在本能的僵尸，最好还是远离。在近距离战斗中，它们相当肉，而且几乎和毒怪僵尸一样强。所以，如果你看到一个闪烁的红灯，一定要小心。特别是在黑暗中。有些肃清者往往会盲目地跟着它走，就好像它是安康鱼的诱饵一样……你们真的有人会上当吗？

jcms.bestiary_zombie_explodingcrab=爆裂蟹
jcms.bestiary_zombie_explodingcrab_desc=可能是由于暴露于辐射而变异，或是经过生物工程改造，会在接触时爆炸的猎头蟹。它们散发出绿光，很容易被发现；尽管如此，它们仍然是我们所知的普通猎头蟹中最危险的品种。它们通过附着在受害者身上来产生“爆炸者”僵尸，但我们不确定这是如何发生的，因为爆裂蟹通常在咬下第一口后会立即消失……也许这需要一定的成熟阶段？不管怎样，如果你碰巧在半空中用电击棍击中一只爆裂蟹，它所包含的能量就可以释放到附近的僵尸身上。伤害虽然不高，但也足以杀死其他猎头蟹并严重伤害僵尸。祝你好运。

jcms.bestiary_zombie_fast=快速僵尸
jcms.bestiary_zombie_fast_desc=乍一看，这种僵尸变种似乎没那么危险，没有皮肤和各种外部组织，但别担心。它们没有肌肉所无法达到的效果，它们会用速度来弥补……以及数量。它们的嚎叫声足以让一些肃清者跪倒在地，但当你看到一大群快速僵尸朝你扑来要撕碎你时？好吧，乞求 Jod 的仁慈，并准备好迎接一场大屠杀。哦，忘了提到它们可以爬墙，并从大约 20 米外像猎豹一样向你扑来。可悲的是，它们早在 127 年前就灭绝了。

jcms.bestiary_zombie_husk=躯壳
jcms.bestiary_zombie_husk_desc=运气不好的家伙们，要么是被猎头蟹伏击，要么就是没有仔细阅读房地产合同。他们前世行动迟缓、愚笨且好斗，现在脑袋上又附着了一只精神控制寄生虫，让情况变得更糟。不过，我们不确定为什么他们全身上下都沾满了血且内脏被掏空，但我们对他们的外表表示赞同，因为它是红色的。给这些僵尸带去好消息吧，告诉他们已经通过了颜色测试，被 J公司 录取了。然后用霰弹枪在他们的脑袋上轰一枪，确保他们能在办公室里重生——这样就大功告成了。不过，如果你射击他们身体的其他任何部位，那会导致猎头蟹脱落。

jcms.bestiary_zombie_minitank=迷你坦克
jcms.bestiary_zombie_minitank_desc=你知道当你被聘为肃清者时，如果你原本不属于 J公司，一旦你开始穿红色的衣服，你就会立刻失去对 J公司 的所有敌意吗？好吧，对这家伙也可以这么说——他曾经是一名职业拳击手，有一天，稍微玩了一下 Cosplay。他仍然困在那个 Cosplay 角色中，因为现在他在脱下 Cosplay 服装之前已经是僵尸的一员了。不过，这并没有让他变得不那么强（尽管他似乎确实像真正的僵尸走得一样慢，而且似乎表现得和僵尸一样愚蠢）。他不能把猎头蟹扔向你（它是个毛绒玩具，尽管这似乎并没有阻止那个毛绒玩具在他死后攻击你），但他他妈的很肉，他的一拳能把任何东西打飞很远，特别是你的炮塔。可悲的是，他仍然穿着 Cosplay 服装重生，所以你必须一直对付他，直到有人最终决定直接把这家伙的帽子摘下来。我们应付他已经很多年了，所以这似乎不太可能发生。我想这跟物理引擎有关系？我不知道。

jcms.bestiary_zombie_poison=毒怪僵尸
jcms.bestiary_zombie_poison_desc=听着。现在是 2925 年。你现在已经玩过《半条命 9》了。你知道这些家伙是干什么的。事实上，他们真的是扫描了一只来制作这些游戏。它们很慢，很肉，还会向你扔剧毒猎头蟹。毒液会造成大量伤害，你的装备会帮你恢复，所以不要问自己为什么在再生，并看在 Jod 的份上，当你看到你的生命值下降时，请不要立刻呼叫医疗空投。只要等一会儿。我知道这很难——我们只要求我们的肃清者有 2 秒钟的注意力持续时间（即使那样，我也听说有肃清者用一根红色冰棍贿赂我们的面试官），但拜托了。另外，请不要他妈的打电话给前台问为什么猎头蟹死后不给你 J币。我们为什么要奖励你干那个？那真的只需要一颗子弹。你认为 J 是长在树上的吗？嗯，我的意思是，它可以长在树上，但你明白我的意思的。

jcms.bestiary_zombie_polyp=息肉
jcms.bestiary_zombie_polyp_desc=长在地上的藤壶怪分支。它们在周围散发红色的毒素云，这会遮挡视线并伤害你。我们其实很想把它们当宠物养，用不祥的红色雾气来污染我们的城市以增加美感，但息肉可能会变得该死地烦人。不管我们对它们大喊多少次不要让气体进入办公室，它们都不在乎。我们希望这种气体至少对经济有用，但不，它没用。所以就这样了，这是战争。杀光它们。走进雾中，把它们开膛破肚。或者随你喜欢，朝红色云层呼叫地毯式轰炸。

jcms.bestiary_zombie_spawner=巢穴
jcms.bestiary_zombie_spawner_desc=长在地板上的恶魔般的增生物，以埋葬在地下的尸体为食。我们还没有费心去进行基础以外的研究，但这些生物似乎从地下吸取尸体，消化任何可食用的部分，然后吐出被我们称为“焦尸 (Charples)”的被附身且烧焦的残骸。它们将几具这样的焦尸团成一个球，然后像迫击炮一样将它射向它们在该区域感觉到的任何干扰源（也就是你）。生成器不会移动，也无法以任何其他方式自卫。如果你听到周期性的、远处的尖叫声……那么你可以判断出周围有生成器存在。当然，你可能也会注意到飞向你的火红焦尸球。生成器害怕爆炸物，所以对它们进行地毯式轰炸或使用 C4 是摆脱它们的确切方法。

jcms.bestiary_zombie_spirit=灵魂
jcms.bestiary_zombie_spirit_desc=这些幽灵是愤怒和痛苦的化身，结合了大量的 J-能量。虽然它们不能靠自己伤害你，但它们可以通过吸收较慢的僵尸，然后将它们在你的附近释放来运输它们。一旦你开始看到僵尸在你面前凭空出现，你就会知道周围有灵魂存在。J公司 曾考虑雇佣这些灵魂来运送人员，但这由于灵魂的无形本质而变得不可能。简单来说，我们无法雇用它们，因为它们没法握笔在合同上签字。