jcms.tutorialmission=教程
jcms.tutorial_speedrun=教程速通

jcms.obj_tutorialphase0=开始入职流程
jcms.obj_tutorialphase1=破门而入
jcms.obj_tutorialphase2=放置一个跳跃垫并跳上去
jcms.obj_tutorialphase3=刷钱以购买加特林炮塔
jcms.obj_tutorialphase4=购买一把武器
jcms.obj_tutorialphase5=呼叫地毯式轰炸
jcms.obj_tutorialphase6=呼叫轨道激光以击杀炮艇
jcms.obj_tutorialphase7=呼叫更多弹药和生命值补充
jcms.obj_tutorialphase8=使用重生信标到达另一边
jcms.obj_tutorialphase9=撤离

jcms.t_nosw_title=你没有电击棍
jcms.t_nosw_desc=你有插件冲突。另一个插件移除了电击棍，我们无法将其发给你。请检查你的插件。

jcms.t_1a_title=入职
jcms.t_2a_desc=欢迎，纳税人。如果你想在杀戮方面变得更有效率一点，请左转。
jcms.t_2a_title=J公司教程场地
jcms.t_3a_desc=你不能去那里。向左走。
jcms.t_3a_title=不是这里，伙计
jcms.t_4a_desc=你将永远拥有电击棍，即使你不想用它。它是你最好的朋友。
jcms.t_4a_title=电击棍
jcms.t_4b_desc=杀戮、破坏、骇入终端。摧毁你面前的木板。
jcms.t_4b_title=用法
jcms.t_5a_desc=你经常需要在任务中骇入物体。例如，这扇连接到终端的门。用电击棍敲击它即可开始骇入。
jcms.t_5a_title=骇客技术
jcms.t_6a_desc=当你敲击终端时，你会得到一个愚蠢的小谜题需要解决。按“使用”键（默认为 [E]）与界面交互，然后动动你的脑子。
jcms.t_6a_title=谜题
jcms.t_7a_desc=这个谜题需要你找到 2 个匹配的数字，然后用线将它们连接起来。在“抓住”一根线后你将无法看到数字，因此你必须记住它们并在采取任何操作之前找到一对。看，这真的很简单。
jcms.t_7a_title=如何解决？
jcms.t_8a_desc=按住上下文菜单（默认为 [C]）并标记这个立方体。
jcms.t_8a_title=标记
jcms.t_9a_desc=标记可以帮助其他肃清者找到你的位置。你可以标记任何东西，甚至包括 NPC 和道具。
jcms.t_9a_title=使用它们！
jcms.t_10a_desc=在左上角你可以看到你的资金 (J)
jcms.t_10a_title=资金
jcms.t_11a_desc=你需要它来使用指令：轨道打击、炸弹、炮塔...... 杀死 NPC 以获得资金。
jcms.t_11a_title=用途
jcms.t_12a_desc=你需要资金。看着弹药箱并按“使用”键（默认为 [E]）来收集它们。
jcms.t_12a_title=无用的弹药 = 资金
jcms.t_13a_desc=1) 瞄准门。\n   2) 按生成菜单键（默认为 [Q]）打开指令轮盘。\n   3) 点击“破门炸药”。
jcms.t_13a_title=指令
jcms.t_14a_desc=有些地图上有锁着的门，而你真的需要通过。幸运的是，有一种方法能把它们他妈的炸开。它实际上适用于所有门，甚至包括大型金属门。
jcms.t_14a_title=破门炸药
jcms.t_15a_desc=你可以将破门炸药附着在道具上，将它们发射得非常远。\n   你也可以将其他爆炸物附着在道具、NPC...... 甚至玩家身上。
jcms.t_15a_title=有趣的事实
jcms.t_16a_desc=在地板上的某处呼叫一个跳跃垫。
jcms.t_16a_title=起飞
jcms.t_17a_desc=它们能让你跳得很高并到达无法触及的地方。如果你在跳跃前蹲下，你会飞得低一些。你也可以将它们附着在墙上。
jcms.t_17a_title=跳跃垫
jcms.t_18a_desc=一旦你购买了加特林炮塔，这扇门就会打开！先杀死牢房里的一些僵尸吧。
jcms.t_18a_title=加特林炮塔
jcms.t_19a_desc=炮塔会分散敌人的注意力并射击它们，在任何情况下都能为你提供巨大帮助。就像一支个人军队。
jcms.t_19a_title=炮塔
jcms.t_20a_desc=滚动鼠标滚轮在多种炮塔类型之间进行选择，然后呼叫一些。
jcms.t_20a_title=选择炮塔类型
jcms.t_20b_desc=杀死足够的僵尸以赚取 950 J。
jcms.t_20b_title=获取一个加特林炮塔
jcms.t_21a_desc=* 用电击棍敲击炮塔可缓慢修复它们。\n   * 在炮塔上按“使用”键（默认为 [E]）可稍微轻推它。\n   * 但你无法为它们补充弹药，所以别白费力气了。
jcms.t_21a_title=炮塔事实
jcms.t_22a_desc=这是你可以购买/出售武器和弹药的地方。\n\n   在每一次任务中，总会至少有一个商店位于地图上的某处。
jcms.t_22a_title=商店
jcms.t_23a_desc=在终端上的武器图标上按“使用”键（默认为 [E]）来购买它。
jcms.t_23a_title=购买武器
jcms.t_24a_desc=每种弹药类型都有不同的价格。手枪比火箭发射器便宜。
jcms.t_24a_title=弹药价格
jcms.t_24b_desc=武装 NPC 经常会掉落冲锋枪(SMG) 和脉冲步枪(AR2) 弹药。如果你选择了合适的武器，你可以节省时间和资金。
jcms.t_24b_title=搜刮！
jcms.t_25a_desc=你的护盾（第二个生命条）在脱战后会再生。
jcms.t_25a_title=护盾
jcms.t_26a_desc=当你的护盾被打破时，寻找掩体并等待它们再生。
jcms.t_26a_title=掩体
jcms.t_27a_desc=有很多不同的类型适用于所有情况，但它们都需要开阔的天空。
jcms.t_27a_title=使用轨道打击
jcms.t_28a_desc=呼叫地毯式轰炸把他们全部炸上天。你需要先赚取 350 J。寻找掩体！
jcms.t_28a_title=地毯式轰炸
jcms.t_29a_desc=用强大的轨道激光干掉炮艇！\n滚动鼠标滚轮来选择它。
jcms.t_29a_title=轨道激光
jcms.t_30a_desc=前往下一个位置，在你的左边。
jcms.t_30a_title=这里完事了
jcms.t_31a_desc=用医疗空投治疗你自己。
jcms.t_31a_title=治疗
jcms.t_32a_desc=用弹药补给箱补充你的弹药。
jcms.t_32a_title=补给
jcms.t_33a_desc=如果你在晴朗的天空下呼叫空投，它们到达的速度会更快。\n   在室内你将不得不等待两倍的时间。J公司讨厌为你打开传送门。
jcms.t_33a_title=去室外
jcms.t_34a_desc=如何在死亡后重生自己和盟友！
jcms.t_34a_title=最后部分
jcms.t_35a_desc=跳下去送死。
jcms.t_35a_title=快乐坑洞
jcms.t_36a_desc=在这堵墙后面放置一个重生信标。在那里重生以继续。
jcms.t_36a_title=重生信标
jcms.t_37a_desc=重生信标是一次性设备，只能复活一名肃清者。\n   如果有多个玩家死亡，他们将按照死亡的顺序重生，即第一个死的人第一个重生。
jcms.t_37a_title=重生顺序
jcms.t_38a_desc=为撤离平台充能并踩上去以完成教程。
jcms.t_38a_title=你准备好了