name: Deploy to Workshop

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: project
      - name: Upload to Workshop
        uses: CFC-Servers/gmod-upload@master
        with:
          id: 3360213737
          changelog: "[AUTO] Updated to the latest GitHub main branch version"
          title: "Map Sweepers"
          type: "gamemode"
          tag1: "build"
          tag2: "fun"
          tag3: "roleplay"
        env:
          STEAM_USERNAME: ${{ secrets.OCTANTISADDONS_STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.OCTANTISADDONS_STEAM_PASSWORD }}
